Board: Initial checklist support
hcengineering/platform pull request #1672
Opened 2022-05-06 06:25 UTC by annano

2022-05-06 12:05 UTC, haiodo requested changes

2022-05-06 12:05 UTC, haiodo commented on packages/ui/src/components/EditWithIcon.svelte
> -  export let icon: Asset | AnySvelteComponent
What the difference with EditBox if icon become optional?

2022-05-06 12:05 UTC, haiodo commented on plugins/board-resources/src/components/EditCard.svelte
> +      checklists = await client.findAll(task.class.TodoItem, { space: object.space, attachedTo: object._id })
You should use live query

2022-05-06 12:05 UTC, haiodo commented on plugins/board-resources/src/components/editor/CardChecklist.svelte
> +    checklistItems = await client.findAll(task.class.TodoItem, { space: value.space, attachedTo: value._id })
Please use live query

2022-05-06 12:05 UTC, haiodo commented on plugins/board-resources/src/components/editor/CardChecklist.svelte
> +    fetch()
No need to fetch if live query is used

2022-05-06 12:05 UTC, haiodo commented on plugins/board-resources/src/components/editor/CardChecklist.svelte
> +  function showItemMenu (item: TodoItem, e?: Event) {
Please use Menu for view and regular actions contribution

2022-05-06 12:05 UTC, haiodo commented on plugins/board-resources/src/components/popups/AddChecklist.svelte
> +    .findAll(board.class.Card, { todoItems: { $gt: 0 } }, { lookup: { _id: { todoItems: task.class.TodoItem } } })
Please use asynchronous/await function

2022-05-11 07:14 UTC, annano commented on packages/ui/src/components/EditWithIcon.svelte
> -  export let icon: Asset | AnySvelteComponent
Reverted

2022-05-11 09:07 UTC, annano commented on plugins/board-resources/src/components/EditCard.svelte
> +      checklists = await client.findAll(task.class.TodoItem, { space: object.space, attachedTo: object._id })
Done

2022-05-11 09:08 UTC, annano commented on plugins/board-resources/src/components/editor/CardChecklist.svelte
> +    checklistItems = await client.findAll(task.class.TodoItem, { space: value.space, attachedTo: value._id })
Done

2022-05-11 09:08 UTC, annano commented on plugins/board-resources/src/components/editor/CardChecklist.svelte
> +    fetch()
Done

2022-05-11 09:08 UTC, annano commented on plugins/board-resources/src/components/editor/CardChecklist.svelte
> +  function showItemMenu (item: TodoItem, e?: Event) {
Updated

2022-05-11 09:36 UTC, annano commented on plugins/board-resources/src/components/popups/AddChecklist.svelte
> +    .findAll(board.class.Card, { todoItems: { $gt: 0 } }, { lookup: { _id: { todoItems: task.class.TodoItem } } })
Updated to `liveQuery`

2022-05-11 17:17 UTC, haiodo approved these changes

2022-05-11 17:17 UTC, merged