Telegram: latest messages below. Update AttachmentPreview layout.
hcengineering/platform pull request #1768
Opened 2022-05-16 15:54 UTC by SasLord

Signed-off-by: Alexander Platov <sas_lord@mail.ru>

2022-05-16 17:22 UTC, BykhovDenis requested changes

2022-05-16 17:22 UTC, BykhovDenis commented on plugins/telegram-resources/src/components/Chat.svelte
> +        sort: { sendOn: SortingOrder.Ascending },
You should get last 500 messages, not first. It should be `Descending`, just use `messages = res.reverse()` in 77

2022-05-17 10:39 UTC, haiodo approved these changes

2022-05-17 10:40 UTC, BykhovDenis approved these changes

2022-05-18 04:05 UTC, haiodo approved these changes

2022-05-18 04:05 UTC, merged