Add open parent issue button for a sub-issue edit panel
hcengineering/platform pull request #2304
Opened 2022-10-13 15:49 UTC by wazsone

Signed-off-by: Ruslan Bayandinov <wazsone@ya.ru>

# Contribution checklist

## Brief description

<img width="739" alt="Screenshot 2022-10-13 at 21 22 36" src="https://user-images.githubusercontent.com/45530296/195643399-a36a7922-3bcc-4932-ac6f-656fc477164e.png">

<img width="750" alt="Screenshot 2022-10-13 at 21 22 55" src="https://user-images.githubusercontent.com/45530296/195643429-8169eee7-940f-4788-8d83-6ee866328141.png">

## Checklist

* [ ] - UI test added to added/changed functionality?
* [x] - Screenshot is added to PR if applicable ?
* [x] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [x] - Does it well tested?
* [x] - Tested for Chrome.
* [x] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [x] - Rebase your branch onto master and upstream branch
* [x] - Is there any redundant or duplicate code?
* [x] - Are required links are linked to PR?
* [x] - Does new code is well documented ?

## Related issues

A list of closed updated issues

2022-10-13 16:33 UTC, BykhovDenis requested changes

2022-10-13 16:33 UTC, BykhovDenis commented on plugins/view-resources/src/components/UpDownNavigator.svelte
> +      showPanel(tracker.component.EditIssue, parentIssue._id, parentIssue._class, 'content')
We need support all doc types, not only issue

2022-10-13 16:33 UTC, BykhovDenis commented on plugins/tracker-resources/src/components/issues/edit/EditIssue.svelte
> +  $: {
'$: parent = issue?.$lookup?.attachedTo' why not?)

2022-10-14 04:24 UTC, wazsone commented on plugins/tracker-resources/src/components/issues/edit/EditIssue.svelte
> +  $: {
@BykhovDenis Thx)
Fixed

2022-10-14 04:24 UTC, wazsone commented on plugins/view-resources/src/components/UpDownNavigator.svelte
> +      showPanel(tracker.component.EditIssue, parentIssue._id, parentIssue._class, 'content')
@BykhovDenis Thank you. Fixed

2022-10-14 07:17 UTC, haiodo commented
@denis-bunakalya I suppose we discussed to remember all panels opened from one, another non closed, and allow to do back to previous opened panel. In this case it should be done in panel.ts and updated in showPanel, close Panel methods.

2022-10-17 02:22 UTC, wazsone commented
@haiodo As far as I recall. We discussed that browser back(or cmd+arrow_back) have that functionality. And this new back button make sense only in a parent/child navigation. 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/45530296/196075045-dde004c5-c5f3-474b-9f74-185eb2b35d6b.png">

2022-10-17 04:59 UTC, haiodo approved these changes

2022-10-18 06:33 UTC, BykhovDenis approved these changes

2022-10-18 06:33 UTC, merged