TSK-1032: add confirmation dialog for projects, fix sprint deleting and allow deleting for Owner or creator only
hcengineering/platform pull request #2964
Opened 2023-04-12 14:28 UTC by ThetaDR

# Contribution checklist

## Brief description
https://front.hc.engineering/workbench/platform/tracker/TSK-1032

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [ ] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [ ] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

A list of closed updated issues

2023-04-12 15:45 UTC, haiodo commented on plugins/tracker-resources/src/index.ts
> +      showPopup(
Why not use generic method to ask for confirmation and delete? Let's remove specialised one. This should be generic for any space. As well it should trigger delete of all child objects in space.

2023-04-14 14:39 UTC, haiodo requested changes
We should have it named archive, and we need unarchive. Please check existing actions for them.

2023-04-14 14:39 UTC, haiodo commented on plugins/tracker-assets/lang/en.json
> +    "DeleteProjectConfirm": "Do you want to delete this project?",
To archive?

2023-04-14 14:39 UTC, haiodo commented on plugins/tracker-resources/src/components/myissues/MyIssues.svelte
> +    return { ...queries[mode], '$lookup.space.archived': false }
I think we need view option here.

2023-04-17 05:42 UTC, haiodo approved these changes

2023-04-17 05:55 UTC, ThetaDR commented on plugins/tracker-resources/src/components/myissues/MyIssues.svelte
> +    return { ...queries[mode], '$lookup.space.archived': false }
Discussed, will be done in another PR

2023-04-17 06:08 UTC, merged