TSK-1158: remove component from sprint. Remove logic for changing component on sprint change
hcengineering/platform pull request #2998
Opened 2023-04-17 11:44 UTC by ThetaDR

# Contribution checklist

## Brief description
https://front.hc.engineering/workbench/platform/tracker/TSK-1158

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [x] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [x] - Does the translations are up to date?
* [ ] - Does it well tested?
* [x] - Tested for Chrome.
* [ ] - Tested for Safari.
* [x] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [x] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

A list of closed updated issues

2023-04-17 14:58 UTC, haiodo approved these changes

2023-04-18 02:38 UTC, haiodo requested changes
Please do not remove component field, and grouping based on it.

2023-04-18 08:18 UTC, haiodo approved these changes

2023-04-18 08:18 UTC, ThetaDR commented
Discussed to fully remove component from sprint

2023-04-18 09:50 UTC, merged