[UBER-196] Fix duplicated project ids when creating a project
hcengineering/platform pull request #3247
Opened 2023-05-24 08:57 UTC by sogorelkov

# Contribution checklist
<img width="749" alt="Screenshot 2023-05-24 at 12 15 42" src="https://github.com/hcengineering/anticrm/assets/105148288/74061eb7-ede4-463f-a662-bfca6ec5ebed">

## Brief description

## Checklist

* [ ] - UI test added to added/changed functionality?
* [x] - Screenshot is added to PR if applicable ?
* [x] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [x] - Does the translations are up to date?
* [x] - Does it well tested?
* [x] - Tested for Chrome.
* [ ] - Tested for Safari.
* [x] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [x] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [x] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

[UBER-196](https://front.hc.engineering/workbench/platform/tracker/UBER-196)

2023-05-24 17:16 UTC, haiodo requested changes
@sogorelkov We need to use apply with validation no project with identifier exists, so it wont be duplicated in any case, and show error to change a name if it exists.

2023-05-26 16:37 UTC, haiodo commented on packages/core/src/tx.ts
> +  notMatched?: boolean
I'm not like to add it here.

2023-05-29 06:48 UTC, sogorelkov commented on packages/core/src/tx.ts
> +  notMatched?: boolean
Reworked.

2023-05-30 06:28 UTC, haiodo approved these changes

2023-05-30 06:28 UTC, merged