[UBER-197] Aggregate components properly
hcengineering/platform pull request #3265
Opened 2023-05-26 20:53 UTC by wazsone

# Contribution checklist

## Related issues
https://front.hc.engineering/workbench/platform/tracker/UBER-197
https://front.hc.engineering/workbench/platform/tracker/UBER-223

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [x] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [x] - Does it well tested?
* [x] - Tested for Chrome.
* [x] - Tested for Safari.
* [x] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [x] - Rebase your branch onto master and upstream branch
* [x] - Is there any redundant or duplicate code?
* [x] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

2023-05-27 01:29 UTC, haiodo requested changes

2023-05-27 01:29 UTC, haiodo commented on packages/presentation/package.json
> +    "@hcengineering/tracker": "^0.6.8"
Presentation is core package and should not know about tracker

2023-05-27 01:29 UTC, haiodo commented on dev/prod/src/platform.ts
> +  addLocation(presentationId, () => import(/* webpackChunkName: "presentation" */ '@hcengineering/presentation/src/resources'))
Why we need it?

2023-05-27 01:29 UTC, haiodo commented on packages/presentation/src/component.ts
> +//
It should be defined in tracker plugin

2023-05-27 01:29 UTC, haiodo commented on packages/presentation/src/component.ts
> +//
Also we need to think in future of how to start use of this pipeline only if tracker plugin is loaded, status support could be move to status plugins as well.

2023-05-27 01:29 UTC, haiodo commented on packages/presentation/src/component.ts
> +export class ComponentMiddleware extends BasePresentationMiddleware implements PresentationMiddleware {
Could we unify this pipeline to support all aggregators via mixin to class, as we have for grouping?

2023-05-27 01:29 UTC, haiodo commented on packages/presentation/src/resources.ts
> +export default async (): Promise<Resources> => ({
Presentation should not be loaded as plugin, I think we need to go try unify aggregator pipeline or move status aggregator to view plugin.

2023-05-27 01:29 UTC, haiodo commented on plugins/tracker-resources/src/plugin.ts
> +    GroupByCategoriesFunc: '' as GroupByCategoriesFunc,
Should it contain Component in name?

2023-05-27 01:29 UTC, haiodo commented on plugins/tracker/src/index.ts
> +    this.byId = toIdMap(components)
Should we hold onto only _id, name, space, color?

2023-05-29 04:05 UTC, wazsone commented on dev/prod/src/platform.ts
> +  addLocation(presentationId, () => import(/* webpackChunkName: "presentation" */ '@hcengineering/presentation/src/resources'))
@haiodo to load ```anticrm/packages/presentation/src/resources.ts```

2023-05-29 04:25 UTC, haiodo commented on dev/prod/src/platform.ts
> +  addLocation(presentationId, () => import(/* webpackChunkName: "presentation" */ '@hcengineering/presentation/src/resources'))
I understand, but we probable could be without it, if generic approach for aggregation will be selected.

2023-05-30 08:30 UTC, haiodo commented on models/view/src/index.ts
> +    GetManager: view.function.GetStatusManager,
It become too complicated, please just have one resource reference.

```js
interface CategoryAggregationView extends Mixin<Class...> {
  groupByCategory: ()=> ...
  groupValues: ()=> ...
 ... and combine with MiddlewareFuncs
}
```

2023-05-30 08:39 UTC, haiodo commented on plugins/view/package.json
> +    "svelte": "3.55.1",
Why we need it here?

2023-05-30 08:39 UTC, haiodo commented on plugins/view/src/index.ts
> +export type GetStore = Resource<<T extends DocManager>() => Writable<T>>
I do think we need to make it more simple and have only one Mixin with all functionality we need to perform aggregation grouping.

2023-05-30 08:40 UTC, haiodo requested changes
A bit more work is required here.

2023-05-30 10:53 UTC, wazsone commented on plugins/view/package.json
> +    "svelte": "3.55.1",
@haiodo To define
```
/**
 * @public
 */
export type GetStore = Resource<<T extends DocManager>() => Writable<T>>
```

2023-05-30 11:02 UTC, haiodo commented on plugins/view/src/index.ts
> +export type GetStore = Resource<<T extends DocManager>() => Writable<T>>
Why you need to return store? Please define function's to get your values.

2023-05-30 11:02 UTC, haiodo commented on plugins/view/package.json
> +    "svelte": "3.55.1",
Why you need to return store? Please define function's to get your values.

2023-05-31 07:31 UTC, haiodo commented on plugins/view/src/index.ts
> +export interface AggregationManager {
Did you plan to always create interfaces like this one?

2023-06-01 12:03 UTC, haiodo approved these changes, later dismissed

2023-06-02 07:10 UTC, BykhovDenis approved these changes

2023-06-06 10:06 UTC, merged