change deprecated package
hcengineering/platform pull request #4145
Opened 2023-12-05 09:43 UTC by BykhovDenis

# Contribution checklist

## Brief description

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [ ] - Does a local formatting is applied (rush format)
* [ ] - Does a local svele-check is applied (rush svelte check)
* [ ] - Does a local UI tests are executed [UI Testing](../tests/readme.md)
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [ ] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [ ] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

A list of closed updated issues

## Contributor requirements

* [ ] - Sign-off is provided. [DCO](https://github.com/apps/dco)
* [ ] - GPG Signature is provided. [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

2023-12-05 09:45 UTC, haiodo approved these changes, later dismissed

2023-12-07 11:30 UTC, aplatoff commented
Denis, this cool

2023-12-07 11:31 UTC, aplatoff commented
Please change something which I do not like

2023-12-07 11:35 UTC, aplatoff requested changes
Please fix

2023-12-07 11:35 UTC, aplatoff commented on packages/ui/src/components/calendar/DateInputBox.svelte
> -      case 'hour':
Do not like this

2023-12-07 11:35 UTC, aplatoff commented on packages/ui/src/components/calendar/DateInputBox.svelte
> -        return timeZone ? moment(date).tz(timeZone).minutes() : moment(date).minutes()
This is bad too

2023-12-07 11:35 UTC, aplatoff commented on packages/ui/src/components/calendar/Month.svelte
>        if (
Improve this

2023-12-07 11:35 UTC, aplatoff commented on packages/ui/src/components/calendar/Month.svelte
> +        zonedTime.day === date.getDate() &&
```suggestion
        zonedTime.day === date.getDate() &&
```

2023-12-07 11:44 UTC, haiodo approved these changes

2023-12-07 11:47 UTC, aplatoff commented on packages/ui/src/components/calendar/DateInputBox.svelte
> -        return timeZone ? moment(date).tz(timeZone).minutes() : moment(date).minutes()
Translate to French

2023-12-07 11:52 UTC, aplatoff commented on packages/ui/src/components/calendar/DateInputBox.svelte
> +        else if (selected === 'hour' && (shouldNext || edits[3].value > 2)) selected = 'minute'
Nice

2023-12-07 11:56 UTC, aplatoff commented
Great Job!

2023-12-26 13:03 UTC, haiodo requested changes

2023-12-26 13:03 UTC, haiodo commented on packages/ui/src/components/calendar/Month.svelte
>        if (
Yes please improve $1

2023-12-26 13:03 UTC, haiodo commented on packages/ui/src/components/calendar/Month.svelte
> +        zonedTime.day === date.getDate() &&
Please improve $2

2024-01-16 11:57 UTC, haiodo commented on packages/ui/src/components/calendar/DateInputBox.svelte
> +        else if (selected === 'hour' && (shouldNext || edits[3].value > 2)) selected = 'minute'
+21213

2024-01-17 07:47 UTC, haiodo commented
@BykhovDenis did you plan to complete it?

2024-01-31 15:07 UTC, closed without merging