4547
hcengineering/platform pull request #4917
Opened 2024-03-10 20:10 UTC by gsdstr

# Contribution checklist

## Brief description

- the current project is passed to key handler
- optimized handler code (approximately 6 times less memory)

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [ ] - Does a local formatting is applied (rush format)
* [ ] - Does a local svelte-check is applied (rush svelte-check)
* [ ] - Does a local UI tests are executed [UI Testing](../tests/readme.md)
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [ ] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [ ] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

#4547

## Contributor requirements

* [x] - Sign-off is provided. [DCO](https://github.com/apps/dco)
* [x] - GPG Signature is provided. [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

2024-03-11 04:30 UTC, BykhovDenis requested changes

2024-03-11 04:30 UTC, BykhovDenis commented on plugins/view-resources/src/components/ActionHandler.svelte
> +      if (isContentEditable && (a.allowedForEditableContent === true)) continue
```suggestion
      if (isContentEditable && (a.allowedForEditableContent !== true)) continue
```

2024-03-12 04:33 UTC, aonnikov commented on plugins/workbench-resources/src/components/Workbench.svelte
> +  <ActionHandler currentSpace={currentSpace}/>
nit: can shorthand it to `<ActionHandler {currentSpace} />`

2024-03-12 04:33 UTC, aonnikov commented on plugins/view-resources/src/components/ActionHandler.svelte
> +        a.keyBinding.find((it) => matchKeySequence(evt, it, t)) !== undefined &&
can we replace all `xx.find(...) !== undefined`  with `xx.some(...)` for clarity?

2024-03-12 07:28 UTC, BykhovDenis approved these changes, later dismissed

2024-03-12 07:32 UTC, aonnikov approved these changes, later dismissed

2024-03-12 09:35 UTC, BykhovDenis approved these changes

2024-03-12 16:57 UTC, merged