UBERF-6163 Store editor content as JSON
hcengineering/platform pull request #5069
Opened 2024-03-27 07:32 UTC by aonnikov

# Contribution checklist

## Brief description

## Checklist

* [ ] - UI test added to added/changed functionality?
* [ ] - Screenshot is added to PR if applicable ?
* [ ] - Does a local formatting is applied (rush format)
* [ ] - Does a local svelte-check is applied (rush svelte-check)
* [ ] - Does a local UI tests are executed [UI Testing](../tests/readme.md)
* [ ] - Does the code work? Check whether function and logic are correct.
* [ ] - Does Changelog.md is updated with changes?
* [ ] - Does the translations are up to date?
* [ ] - Does it well tested?
* [ ] - Tested for Chrome.
* [ ] - Tested for Safari.
* [ ] - Go through the changed code looking for typos, TODOs, commented LOCs, debugging pieces of code, etc.
* [ ] - Rebase your branch onto master and upstream branch
* [ ] - Is there any redundant or duplicate code?
* [ ] - Are required links are linked to PR?
* [ ] - Does new code is well documented ?

## Related issues

A list of closed updated issues

## Contributor requirements

* [ ] - Sign-off is provided. [DCO](https://github.com/apps/dco)
* [ ] - GPG Signature is provided. [GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

2024-03-28 14:26 UTC, haiodo requested changes

2024-03-28 14:26 UTC, haiodo commented on models/text-editor/src/migration.ts
> +    const docs = await client.find(domain, { _class })
please use iteration bulk api, it will not fit into men for huge workspaces.

2024-03-28 14:26 UTC, haiodo commented on plugins/view-resources/src/components/MarkupPresenter.svelte
> +  <!-- <MessageViewer message={value ?? ''} /> -->
????

2024-03-28 14:26 UTC, haiodo commented on models/text-editor/src/migration.ts
> +    const docs = await client.find(domain, { _class })
please also check on alex stuff db for performance

2024-03-28 14:35 UTC, aonnikov commented on plugins/view-resources/src/components/MarkupPresenter.svelte
> +  <!-- <MessageViewer message={value ?? ''} /> -->
It is by mistake :)

2024-03-29 13:59 UTC, aonnikov commented on models/text-editor/src/migration.ts
> +    const docs = await client.find(domain, { _class })
Some performance numbers from alex staff db. In total it took about 30 minutes on my laptop:
```
migrate: { workspaceId: 'ws30', operation: 'activity', time: 94479 }
migrate: { workspaceId: 'ws30', operation: 'calendar', time: 159 }
migrate: { workspaceId: 'ws30', operation: 'task', time: 155 }
migrate: { workspaceId: 'ws30', operation: 'textEditorOperation', time: 1531386 }
```

2024-03-29 14:20 UTC, haiodo commented on models/text-editor/src/migration.ts
> +    const docs = await client.find(domain, { _class })
ouch, could track why so long?

2024-03-29 14:33 UTC, aonnikov commented on models/text-editor/src/migration.ts
> +    const docs = await client.find(domain, { _class })
yeah, will try, but I have nothing to compare these numbers with

2024-04-09 10:01 UTC, haiodo approved these changes, later dismissed

2024-04-11 07:13 UTC, haiodo approved these changes

2024-04-11 07:13 UTC, merged