Fix: Tests and Fix for user enumeration bug
hcengineering/platform pull request #5229
Opened 2024-04-07 04:58 UTC by PvtSec

## Changes made:
- Add test coverage for invalid logins
- Add fix for the issue: [user enumeration bug via login](https://github.com/hcengineering/platform/issues/5202)

2024-04-09 11:00 UTC, haiodo approved these changes

2024-04-09 11:04 UTC, haiodo requested changes
Hi @PvtSec 
Thanks for a contribution, but some work is still to be done accept changes. Thanks.

2024-04-09 11:04 UTC, haiodo commented on README.md
> +- [Huly Platform](#huly-platform)
Let's remove this changes from this PR. Thanks.

2024-04-09 11:04 UTC, haiodo commented on .github/workflows/main.yml
> +        uses: peaceiris/actions-gh-pages@v3.9.3
Let's remove this file changes in this PR.

2024-04-09 11:04 UTC, haiodo commented on server/account/src/index.ts
> -    throw new PlatformError(new Status(Severity.ERROR, platform.status.AccountNotFound, { account: email }))
I think we still need log states, InvalidPassword into context logger and pass them into analytics, so we could understand and track a problems.

2024-04-14 06:54 UTC, PvtSec commented
Hi @haiodo ,

- Reverted changes
- Keeps logging for older states
- Resolved all comments.

Ready for a new review

2024-06-15 17:28 UTC, closed without merging